/**
 * O catálogo declarado — a lista do que **deveria** existir, atributo a atributo.
 *
 * ---------------------------------------------------------------------------
 * Por que ele precisou existir
 * ---------------------------------------------------------------------------
 * A Cobertura sabia responder "dos atributos que a DRE cita, quantos vieram
 * preenchidos?". Não sabia responder a pergunta que o produto promete na
 * própria tela: *o que já temos versus o que deveríamos ter*. A diferença entre
 * as duas é o tamanho do universo, e o universo era pequeno demais por
 * construção — o plano da DRE cita **10** códigos de atributo, e todo o resto do
 * esperado saía de inferência sobre o que já havia chegado.
 *
 * Inferir o esperado a partir do que chegou tem um limite que nenhum ajuste de
 * limiar resolve: **o que nunca chegou é invisível.** Uma coluna que a fonte
 * deveria mandar e nunca mandou não aparece no histórico, não aparece na
 * estrutura, e portanto não aparece como lacuna. A Cobertura media a
 * completude do arquivo recebido, não a do universo.
 *
 * Este arquivo é o universo, escrito. São os 250 atributos que as três
 * planilhas de curadoria em `docs/` declaram para os três tipos de linha —
 * `planilha-atributos-cavalo-dre.xlsx`, `-carreta-` e `-frete-`. Elas já eram a
 * declaração; só não eram alcançáveis por código.
 *
 * ---------------------------------------------------------------------------
 * Por que em TypeScript, e não lido do .xlsx em tempo de execução
 * ---------------------------------------------------------------------------
 * Pelo mesmo motivo que `lib/db/src/semantica-confirmada.ts` escolheu isto para
 * as confirmações canônicas, e a frase de lá vale inteira aqui: guardá-la só no
 * banco a tornaria invisível à revisão e perdida a cada base nova; mantê-la
 * aqui a torna diffável, atribuível e reaplicável em qualquer ambiente.
 *
 * Um universo esperado que muda porque alguém salvou um arquivo em `docs/` é um
 * denominador que se move sem revisão — e o denominador é metade de todo número
 * que a tela de Cobertura mostra. Aqui, acrescentar um atributo ao universo é
 * uma linha num pull request, com quem pediu e por quê no corpo dele.
 *
 * As planilhas continuam sendo o documento de origem, e continuam sendo o que a
 * curadoria em lote lê e escreve (`planilha-de-atributos.ts`). Este arquivo é a
 * projeção delas sob revisão.
 *
 * ---------------------------------------------------------------------------
 * O que este catálogo **não** faz
 * ---------------------------------------------------------------------------
 * - **Não cria atributo.** `attribute` continua nascendo da importação, de
 *   célula com valor, como `planilha-de-atributos.ts` documenta e protege. Um
 *   código daqui que nunca foi importado não vira linha lá: ele vira
 *   *expectativa* em `coverage_expectation`, que é outra tabela e outra
 *   pergunta. É por isso que `coverage_expectation.attribute_code` é texto sem
 *   chave estrangeira — a expectativa antecede o dado, e tem de poder existir
 *   sem ele.
 * - **Não afirma significado.** `nomeGerencial` é rótulo de leitura, para que
 *   uma lacuna de trecho apareça como "Pedágio" e não como
 *   `trecho.pedagio`. Ele nunca escreve `attribute.display_name`, nunca escreve
 *   `attribute_semantics`, e não destrava soma nenhuma. Unidade, periodicidade
 *   e base de cálculo continuam vindo da confirmação humana — o portão que
 *   `attribute.semantics_status` guarda.
 * - **Não decide criticidade.** A seção da DRE que cada linha carrega é a
 *   classificação da própria planilha, e serve para uma coisa só: separar o que
 *   entra na DRE do que é cadastral. Quem é *crítico* continua sendo definido
 *   em `lib/dre/src/plano.ts`, por alimentar um componente `essencial` — uma
 *   regra, um dono, como `contrato.ts` argumenta.
 *
 * ---------------------------------------------------------------------------
 * Os códigos
 * ---------------------------------------------------------------------------
 * `code` é gerado da mesma forma que a importação o geraria:
 * `${entityType.toLowerCase()}.${slugifyColumn(sourceName)}`, a regra de
 * `lib/ingest/src/pipeline.ts`. Isso não é conveniência — é a condição para o
 * catálogo servir de expectativa. Um código divergente produziria uma lacuna
 * que nunca fecha: o dado chegaria com um nome e a expectativa cobraria outro,
 * para sempre.
 *
 * `catalogo-declarado.test.ts` prova a igualdade nos dois sentidos: que os
 * códigos daqui sobrevivem a `slugifyColumn` e que os 10 que o plano da DRE
 * cita existem neste catálogo. Um `sourceName` corrigido que mude o slug quebra
 * o teste no mesmo commit, em vez de silenciosamente abrir uma lacuna eterna.
 */

/** Os três tipos de linha que as planilhas declaram. */
export type TipoDeclarado = "CAVALO" | "CARRETA" | "TRECHO";

/** Um atributo que a fonte deveria entregar. */
export interface AtributoDeclarado {
  entityType: TipoDeclarado;
  /** Como em `attribute.code`. Derivado de `sourceName` pela regra da importação. */
  code: string;
  /** O cabeçalho literal da coluna, como a planilha o escreve. */
  sourceName: string;
  /** Rótulo de leitura. Nunca escreve `attribute.display_name`. */
  nomeGerencial: string | null;
  /** A seção da DRE, ou `"Não entra na DRE"` para o que é cadastral. */
  secaoDaDRE: string | null;
  /** A linha analítica dentro da seção. */
  categoriaDaDRE: string | null;
}

/** O rótulo que a planilha usa para o que não alimenta a DRE. */
export const FORA_DA_DRE = "Não entra na DRE";

/**
 * O atributo alimenta alguma linha da DRE?
 *
 * O que responde `false` aqui é cadastral — placa, CNPJ, vigência, modelo. Ele
 * continua sendo esperado (a sua ausência é uma lacuna de verdade: sem placa
 * não há entidade), mas entra como `INFORMATIVO` e por isso não mexe na
 * cobertura crítica, que é o número que decide se a análise financeira pode
 * rodar.
 */
export function entraNaDRE(atributo: AtributoDeclarado): boolean {
  return atributo.secaoDaDRE !== null && atributo.secaoDaDRE !== FORA_DA_DRE;
}

/**
 * Os 250 atributos, na ordem das planilhas.
 *
 * A contagem por tipo — 76 cavalo, 64 carreta, 110 trecho — está no teste, e
 * não num comentário: um número escrito à mão aqui envelheceria no primeiro
 * atributo acrescentado.
 */
export const CATALOGO_DECLARADO: AtributoDeclarado[] = [
  // --- CAVALO ---
  {
    entityType: "CAVALO",
    code: "cavalo.vigencia",
    sourceName: "Vigencia",
    nomeGerencial: "Quinzena",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.unidade_cnpj",
    sourceName: "Unidade - CNPJ",
    nomeGerencial: "CNPJ da Unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.unidade_nome",
    sourceName: "Unidade - Nome",
    nomeGerencial: "Nome da Unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.unidade_sap",
    sourceName: "Unidade SAP",
    nomeGerencial: "Codigo da unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.unidade_tms",
    sourceName: "Unidade TMS",
    nomeGerencial: "Código TMS da Unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.unidade_promax_unb",
    sourceName: "Unidade - Promax UNB",
    nomeGerencial: "UNB Promax da Unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.unidade_regional",
    sourceName: "Unidade - Regional",
    nomeGerencial: "Regional da Unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.operador_cnpj",
    sourceName: "Operador - CNPJ",
    nomeGerencial: "CNPJ do Transportador",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.operador_nome",
    sourceName: "Operador - Nome",
    nomeGerencial: "Nome do Transportador",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.operador_sap",
    sourceName: "Operador - SAP",
    nomeGerencial: "Codigo do Transportador",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.operador_tms",
    sourceName: "Operador - TMS",
    nomeGerencial: "Código TMS do Transportador",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.operador_promax",
    sourceName: "Operador - Promax",
    nomeGerencial: "Código Promax do Transportador",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.organizacao_de_compras",
    sourceName: "Organizacao de Compras",
    nomeGerencial: "Organização de Compras",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.prazo_pagamento",
    sourceName: "Prazo Pagamento",
    nomeGerencial: "Prazo de Pagamento",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.custo_variavel_simulado",
    sourceName: "Custo Variável Simulado",
    nomeGerencial: "Custo variavel simulado do veiculo",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Outros",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.empresa_locadora",
    sourceName: "Empresa locadora",
    nomeGerencial: "Empresa de locação do veiculo",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.ganhador_bid",
    sourceName: "Ganhador BID",
    nomeGerencial: "Ganhador do bid de compra",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.padrao",
    sourceName: "Padrão",
    nomeGerencial: "Padrao do veiculo",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.placa",
    sourceName: "Placa",
    nomeGerencial: "Placa",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.placa_carreta",
    sourceName: "Placa Carreta",
    nomeGerencial: "Placa implemento",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.spread_bndes",
    sourceName: "Spread BNDES",
    nomeGerencial: "Spread bnds compra",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Premissas do financiamento",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.spread_banco",
    sourceName: "Spread Banco",
    nomeGerencial: "Spread banco compra",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Premissas do financiamento",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.tjlp",
    sourceName: "TJLP",
    nomeGerencial: "Tjlp da compra mais inpc",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Premissas do financiamento",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.taxa_finame",
    sourceName: "Taxa Finame (%)",
    nomeGerencial: "Saoma dos spread + tjlp",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Premissas do financiamento",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.amortizacao_cavalo",
    sourceName: "amortizacaoCavalo",
    nomeGerencial: "CALCULO DA AMORTIZAÇÃO DO VEICULO ATÉ O 60º MÊS DE FINANCIAMENTO",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Amortização do principal (FINAME)",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.ano",
    sourceName: "ano",
    nomeGerencial: "Ano da compra do veiculo ( transformado em data)",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.ano_bid",
    sourceName: "anoBid",
    nomeGerencial: "Ano do bid",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.ativo",
    sourceName: "ativo",
    nomeGerencial: "Veiculo ativo ou não ativo ( check mensal)",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.cambio",
    sourceName: "cambio",
    nomeGerencial: "Tipo do cambio do veiculo",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.carencia",
    sourceName: "carencia",
    nomeGerencial: "Carencia de finame",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Premissas do financiamento",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.chassi",
    sourceName: "chassi",
    nomeGerencial: "Chassi do veiculo",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.ciclo",
    sourceName: "ciclo",
    nomeGerencial: "Ciclo do veiculo",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.combustivel_capacidade",
    sourceName: "combustivelCapacidade",
    nomeGerencial: "Capacidade de pallets para calculo de combustivel",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.combustivel_consumo_benchmark",
    sourceName: "combustivelConsumoBenchmark",
    nomeGerencial: "Média do veiculo benchmark",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Combustível",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.combustivel_consumo_neg",
    sourceName: "combustivelConsumoNeg",
    nomeGerencial: "Média de combustivel revisão trimestral",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Combustível",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.combustivel_consumo_neg_inteiro",
    sourceName: "combustivelConsumoNegInteiro",
    nomeGerencial: "Check de média conforme negociada",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Combustível",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.combustivel_percentual_perda_vida",
    sourceName: "combustivelPercentualPerdaVida",
    nomeGerencial: "Calculo de perda de consumo conforme vida do veiculo",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Combustível",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.combustivel_vida_cavalo",
    sourceName: "combustivelVidaCavalo",
    nomeGerencial: "Calculo da vida do veiculo conforme data de compra",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.custo_aluguel",
    sourceName: "custoAluguel",
    nomeGerencial: "Custo de aluguel caso veiculo seja leasing",
    secaoDaDRE: "(−) Custo fixo",
    categoriaDaDRE: "Aluguel do veículo",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.data",
    sourceName: "data",
    nomeGerencial: "Data de entrada do veiculo no freightech",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.data_fim_contrato",
    sourceName: "dataFimContrato",
    nomeGerencial: "Data de projeção de fim de contrato",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.eixo_empurrada",
    sourceName: "eixoEmpurrada",
    nomeGerencial: "Tipo de eixos frota",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.faixa_km",
    sourceName: "faixaKm",
    nomeGerencial: "Faixa de km do veiculo",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.finame_cavalo",
    sourceName: "finameCavalo",
    nomeGerencial: "Calculo do finame ( amortização + juros finame)",
    secaoDaDRE: "Receita bruta",
    categoriaDaDRE: "Remuneração fixa do cavalo",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.free_maintenance",
    sourceName: "freeMaintenance",
    nomeGerencial: "Carencia de manutenção",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.frota_emprestada",
    sourceName: "frotaEmprestada",
    nomeGerencial: "Check se frota é emprestada",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.ipva_licenciamento",
    sourceName: "ipvaLicenciamento",
    nomeGerencial: "Calculo do ipva ou licenciamento anual( revisão semestral)",
    secaoDaDRE: "(−) Custo fixo",
    categoriaDaDRE: "IPVA e licenciamento",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.juros_finame_cavalo",
    sourceName: "jurosFinameCavalo",
    nomeGerencial: "Juros do finame",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Juros do FINAME",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.lucro_fixomodelo_novo_ciclo_cavalo",
    sourceName: "lucroFixomodeloNovoCicloCavalo",
    nomeGerencial: "Calculo do lucro fixo do veiculo",
    secaoDaDRE: "Receita bruta",
    categoriaDaDRE: "Remuneração fixa do cavalo",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.lucro_variavel_previsto_cavalo",
    sourceName: "lucroVariavelPrevistoCavalo",
    nomeGerencial: "Calculo do lucro variavel do veiculo previsto",
    secaoDaDRE: "Receita bruta",
    categoriaDaDRE: "Remuneração variável / produtividade (não confirmada — não soma)",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.manutencao_ano",
    sourceName: "manutencaoAno",
    nomeGerencial: "Calculo para ano do bid",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.manutencao_bid",
    sourceName: "manutencaoBid",
    nomeGerencial: "Busca do valor por ano caso veiculo não tenha contrato de manutenção e tenha compra autorizada fora do bid",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.manutencao_compra_fora_do_bid_autorizada",
    sourceName: "manutencaoCompraForaDoBidAutorizada",
    nomeGerencial: "Check de compra fora do bid",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.manutencao_contrato",
    sourceName: "manutencaoContrato",
    nomeGerencial: "Valor do contrato de manutenção com valor reajustado ( crédito de pis e cofins)",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.manutencao_free_maintenance",
    sourceName: "manutencaoFreeMaintenance",
    nomeGerencial: "Check de campo de carencia de manutenção",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.manutencao_reais_km",
    sourceName: "manutencaoReaisKm",
    nomeGerencial: "Calculo de r$ de manutenção cavalo",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.manutencao_reais_km_inteiro",
    sourceName: "manutencaoReaisKmInteiro",
    nomeGerencial: "Check de validação de km inteiro para manutenção cavalo",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.manutencao_vida_meses",
    sourceName: "manutencaoVidaMeses",
    nomeGerencial: "Calculo de vida do veiculo para manutenção de cavalo",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.mes_de_entrada",
    sourceName: "mesDeEntrada",
    nomeGerencial: "Mês de entrada do veiculo no freightech",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.modelo_empurrada",
    sourceName: "modeloEmpurrada",
    nomeGerencial: "Modelo de caminhão",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.montadora",
    sourceName: "montadora",
    nomeGerencial: "Montadora do veiculo",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.odometro_entrada",
    sourceName: "odometroEntrada",
    nomeGerencial: "Kilometragem atual do veiculo",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.percentual_entrada",
    sourceName: "percentualEntrada",
    nomeGerencial: "Calculo para % de entrada para veiculos comprados após 2018",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Premissas do financiamento",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.percentual_icms",
    sourceName: "percentualIcms",
    nomeGerencial: "% De icms conforme compra do veiculo",
    secaoDaDRE: "(−) Deduções",
    categoriaDaDRE: "ICMS sobre a prestação",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.percentual_reajuste_aplicado",
    sourceName: "percentualReajusteAplicado",
    nomeGerencial: "Calculo de % aplicado sobre a faixa de km para contrato de manutenção",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.periodo_finame",
    sourceName: "periodoFiname",
    nomeGerencial: "Periodo de finame do veiculo",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Premissas do financiamento",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.pneu_medida_empurrada",
    sourceName: "pneuMedidaEmpurrada",
    nomeGerencial: "Medida do pneu do cavalo",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pneus",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.reaiskm",
    sourceName: "reaiskm",
    nomeGerencial: "R$ km manutenção conforme contrato",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.regiao_empurrada",
    sourceName: "regiaoEmpurrada",
    nomeGerencial: "Região de operação",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.status_financiamento_t1_shared",
    sourceName: "statusFinanciamentoT1Shared",
    nomeGerencial: "Status financiamento",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.tipo_combustivel_empurrada",
    sourceName: "tipoCombustivelEmpurrada",
    nomeGerencial: "Tipo de modelo de consumo de combustivel",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Combustível",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.valor_icms",
    sourceName: "valorIcms",
    nomeGerencial: "Calculo para crédito de icms sobre insumos",
    secaoDaDRE: "(−) Deduções",
    categoriaDaDRE: "ICMS sobre a prestação",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.valor_nf_compra",
    sourceName: "valorNfCompra",
    nomeGerencial: "Valor de compra da nota fiscal",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Grandeza de aquisição (não entra na DRE do período)",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.valor_pis_cofins",
    sourceName: "valorPisCofins",
    nomeGerencial: "Valor de pis cofins sobre o valor de nota fiscal de compra",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Grandeza de aquisição (não entra na DRE do período)",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.valor_pneu",
    sourceName: "valorPneu",
    nomeGerencial: "Valor de pneus conforme compra",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pneus",
  },
  {
    entityType: "CAVALO",
    code: "cavalo.valor_reajustado",
    sourceName: "valorReajustado",
    nomeGerencial: "Calculo do valor reajustado de reais km",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  // --- CARRETA ---
  {
    entityType: "CARRETA",
    code: "carreta.vigencia",
    sourceName: "Vigencia",
    nomeGerencial: "Quinzena",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.unidade_cnpj",
    sourceName: "Unidade - CNPJ",
    nomeGerencial: "CNPJ da Unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.unidade_nome",
    sourceName: "Unidade - Nome",
    nomeGerencial: "Nome da Unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.unidade_sap",
    sourceName: "Unidade SAP",
    nomeGerencial: "Codigo da unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.unidade_tms",
    sourceName: "Unidade TMS",
    nomeGerencial: "Código TMS da Unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.unidade_promax_unb",
    sourceName: "Unidade - Promax UNB",
    nomeGerencial: "UNB Promax da Unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.unidade_regional",
    sourceName: "Unidade - Regional",
    nomeGerencial: "Regional da Unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.operador_cnpj",
    sourceName: "Operador - CNPJ",
    nomeGerencial: "CNPJ do Transportador",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.operador_nome",
    sourceName: "Operador - Nome",
    nomeGerencial: "Nome do Transportador",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.operador_sap",
    sourceName: "Operador - SAP",
    nomeGerencial: "Codigo do Transportador",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.operador_tms",
    sourceName: "Operador - TMS",
    nomeGerencial: "Código TMS do Transportador",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.operador_promax",
    sourceName: "Operador - Promax",
    nomeGerencial: "Código Promax do Transportador",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.organizacao_de_compras",
    sourceName: "Organizacao de Compras",
    nomeGerencial: "Organização de Compras",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.prazo_pagamento",
    sourceName: "Prazo Pagamento",
    nomeGerencial: "Prazo de Pagamento",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.empresa_locadora",
    sourceName: "Empresa locadora",
    nomeGerencial: "Custo variavel simulado do veiculo",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.placa",
    sourceName: "Placa",
    nomeGerencial: "Placa implemento",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.spread_bndes",
    sourceName: "Spread BNDES",
    nomeGerencial: "Spread banco implemento",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Premissas do financiamento",
  },
  {
    entityType: "CARRETA",
    code: "carreta.spread_banco",
    sourceName: "Spread Banco",
    nomeGerencial: "Sprea d banco implemento",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Premissas do financiamento",
  },
  {
    entityType: "CARRETA",
    code: "carreta.tjlp",
    sourceName: "TJLP",
    nomeGerencial: "Tjlp entrada implemento",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Premissas do financiamento",
  },
  {
    entityType: "CARRETA",
    code: "carreta.taxa_finame",
    sourceName: "Taxa Finame (%)",
    nomeGerencial: "Taxa  finamet(%)",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Premissas do financiamento",
  },
  {
    entityType: "CARRETA",
    code: "carreta.amortizacao_implemento",
    sourceName: "amortizacaoImplemento",
    nomeGerencial: "Amortização",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Amortização do principal (FINAME)",
  },
  {
    entityType: "CARRETA",
    code: "carreta.ano",
    sourceName: "ano",
    nomeGerencial: "Ano entrada implemento",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.capacidade_empurrada",
    sourceName: "capacidadeEmpurrada",
    nomeGerencial: "Capacidade para calculo de custo variavel",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.capacidade_pallets_real_empurrada",
    sourceName: "capacidadePalletsRealEmpurrada",
    nomeGerencial: "Capacidade real da carreta",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.carencia",
    sourceName: "carencia",
    nomeGerencial: "Carência do FINAME",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Premissas do financiamento",
  },
  {
    entityType: "CARRETA",
    code: "carreta.chassi",
    sourceName: "chassi",
    nomeGerencial: "Chassi implemento",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.ciclo",
    sourceName: "ciclo",
    nomeGerencial: "Ciclo do implemento",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.custo_aluguel",
    sourceName: "custoAluguel",
    nomeGerencial: "Custo aluguel implemento",
    secaoDaDRE: "(−) Custo fixo",
    categoriaDaDRE: "Aluguel de implemento (não confirmado — não soma)",
  },
  {
    entityType: "CARRETA",
    code: "carreta.custo_fixo",
    sourceName: "custoFixo",
    nomeGerencial: "Custo fixo implemento",
    secaoDaDRE: "Receita bruta",
    categoriaDaDRE: "Remuneração fixa do conjunto (não somar na carreta)",
  },
  {
    entityType: "CARRETA",
    code: "carreta.data",
    sourceName: "data",
    nomeGerencial: "Data entrada implemento",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.data_fim_contrato",
    sourceName: "dataFimContrato",
    nomeGerencial: "Data fim de contrato implemento",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.double_deck",
    sourceName: "doubleDeck",
    nomeGerencial: "Double fara calculo check custo variavel",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.eixo_empurrada",
    sourceName: "eixoEmpurrada",
    nomeGerencial: "Tipo de eixo empurrada - carreta",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.faixa_reflexiva",
    sourceName: "faixaReflexiva",
    nomeGerencial: "Calculo de faixa refletiva carreta",
    secaoDaDRE: "(−) Custo fixo",
    categoriaDaDRE: "Itens obrigatórios do implemento",
  },
  {
    entityType: "CARRETA",
    code: "carreta.finame",
    sourceName: "finame",
    nomeGerencial: "Finame cavalo + implemento",
    secaoDaDRE: "Receita bruta",
    categoriaDaDRE: "Remuneração fixa do conjunto (não somar na carreta)",
  },
  {
    entityType: "CARRETA",
    code: "carreta.finame_implemento",
    sourceName: "finameImplemento",
    nomeGerencial: "Finame do implemento",
    secaoDaDRE: "Receita bruta",
    categoriaDaDRE: "Remuneração fixa da carreta",
  },
  {
    entityType: "CARRETA",
    code: "carreta.frota_emprestada",
    sourceName: "frotaEmprestada",
    nomeGerencial: "Implemento emprestado?",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.icms",
    sourceName: "icms",
    nomeGerencial: "Icms entrada implemento",
    secaoDaDRE: "(−) Deduções",
    categoriaDaDRE: "ICMS sobre a prestação",
  },
  {
    entityType: "CARRETA",
    code: "carreta.implemento",
    sourceName: "implemento",
    nomeGerencial: "Montadora",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.ipva_licenciamento",
    sourceName: "ipvaLicenciamento",
    nomeGerencial: "Ipva e licenciamento da frota",
    secaoDaDRE: "(−) Custo fixo",
    categoriaDaDRE: "IPVA e licenciamento",
  },
  {
    entityType: "CARRETA",
    code: "carreta.ipva_licenciamento_mensal",
    sourceName: "ipvaLicenciamentoMensal",
    nomeGerencial: "Valor mensal de licenciamento",
    secaoDaDRE: "(−) Custo fixo",
    categoriaDaDRE: "Licenciamento mensal (não confirmado — não soma)",
  },
  {
    entityType: "CARRETA",
    code: "carreta.juros_finame_implemento",
    sourceName: "jurosFinameImplemento",
    nomeGerencial: "Juros de finame implemento",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Juros do FINAME",
  },
  {
    entityType: "CARRETA",
    code: "carreta.lucro_fixomodelo_novo_ciclo",
    sourceName: "lucroFixomodeloNovoCiclo",
    nomeGerencial: "Calculo lucro fixo  conjunto",
    secaoDaDRE: "Receita bruta",
    categoriaDaDRE: "Remuneração fixa do conjunto (não somar na carreta)",
  },
  {
    entityType: "CARRETA",
    code: "carreta.lucro_fixomodelo_novo_ciclo_carreta",
    sourceName: "lucroFixomodeloNovoCicloCarreta",
    nomeGerencial: "Calculo lucro fixo  implemento",
    secaoDaDRE: "Receita bruta",
    categoriaDaDRE: "Remuneração fixa da carreta",
  },
  {
    entityType: "CARRETA",
    code: "carreta.lucro_variavel_previsto",
    sourceName: "lucroVariavelPrevisto",
    nomeGerencial: "Lucro variavel previsto conjunto",
    secaoDaDRE: "Receita bruta",
    categoriaDaDRE: "Remuneração variável do conjunto (não confirmada — não soma)",
  },
  {
    entityType: "CARRETA",
    code: "carreta.lucro_variavel_previsto_carreta",
    sourceName: "lucroVariavelPrevistoCarreta",
    nomeGerencial: "Lucro variavel previsto implemento",
    secaoDaDRE: "Receita bruta",
    categoriaDaDRE: "Remuneração variável da carreta (não confirmada — não soma)",
  },
  {
    entityType: "CARRETA",
    code: "carreta.mes_de_entrada",
    sourceName: "mesDeEntrada",
    nomeGerencial: "Mês de entrada implemento",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.modelo",
    sourceName: "modelo",
    nomeGerencial: "Modelo da carreta",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.percentual_entrada",
    sourceName: "percentualEntrada",
    nomeGerencial: "% De entrada da compra do veiculo após 2018",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Premissas do financiamento",
  },
  {
    entityType: "CARRETA",
    code: "carreta.percentual_icms",
    sourceName: "percentualIcms",
    nomeGerencial: "% De icms conforme parametro da região da operação",
    secaoDaDRE: "(−) Deduções",
    categoriaDaDRE: "ICMS sobre a prestação",
  },
  {
    entityType: "CARRETA",
    code: "carreta.periodo_finame",
    sourceName: "periodoFiname",
    nomeGerencial: "Periodo finame compra",
    secaoDaDRE: "(−) Depreciação e financeiro",
    categoriaDaDRE: "Premissas do financiamento",
  },
  {
    entityType: "CARRETA",
    code: "carreta.pis_cofins",
    sourceName: "pisCofins",
    nomeGerencial: "Pis cofins",
    secaoDaDRE: "(−) Deduções",
    categoriaDaDRE: "PIS/COFINS sobre a prestação",
  },
  {
    entityType: "CARRETA",
    code: "carreta.pneu_medida_empurrada",
    sourceName: "pneuMedidaEmpurrada",
    nomeGerencial: "Medida de pneus",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pneus",
  },
  {
    entityType: "CARRETA",
    code: "carreta.rastreador",
    sourceName: "rastreador",
    nomeGerencial: "Veiculo tem rastreador?",
    secaoDaDRE: "(−) Custo fixo",
    categoriaDaDRE: "Rastreamento e telemetria",
  },
  {
    entityType: "CARRETA",
    code: "carreta.revestimento",
    sourceName: "revestimento",
    nomeGerencial: "Revestimento da carreta - calculo",
    secaoDaDRE: "(−) Custo fixo",
    categoriaDaDRE: "Itens obrigatórios do implemento",
  },
  {
    entityType: "CARRETA",
    code: "carreta.seguro",
    sourceName: "seguro",
    nomeGerencial: "Seguro da carreta",
    secaoDaDRE: "(−) Custo fixo",
    categoriaDaDRE: "Seguro (não confirmado — não soma)",
  },
  {
    entityType: "CARRETA",
    code: "carreta.status_financiamento",
    sourceName: "statusFinanciamento",
    nomeGerencial: "Status de financimento da placa",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.status_financiamento_t1_shared",
    sourceName: "statusFinanciamentoT1Shared",
    nomeGerencial: "Status de financiamento para fim t1",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.tacografo",
    sourceName: "tacografo",
    nomeGerencial: "Check de tacografo",
    secaoDaDRE: "(−) Custo fixo",
    categoriaDaDRE: "Itens obrigatórios do implemento",
  },
  {
    entityType: "CARRETA",
    code: "carreta.tipo_carroceria_empurrada",
    sourceName: "tipoCarroceriaEmpurrada",
    nomeGerencial: "Tipo e modelo de carroceria",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "CARRETA",
    code: "carreta.valor_icms",
    sourceName: "valorIcms",
    nomeGerencial: "Valor de icms conforme compra",
    secaoDaDRE: "(−) Deduções",
    categoriaDaDRE: "ICMS sobre a prestação",
  },
  {
    entityType: "CARRETA",
    code: "carreta.valor_nf_compra",
    sourceName: "valorNfCompra",
    nomeGerencial: "Valor de compra da placa",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Grandeza de aquisição (não entra na DRE do período)",
  },
  {
    entityType: "CARRETA",
    code: "carreta.valor_pis_cofins",
    sourceName: "valorPisCofins",
    nomeGerencial: "Valor de pis e cofins da nota de compra",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Grandeza de aquisição (não entra na DRE do período)",
  },
  {
    entityType: "CARRETA",
    code: "carreta.valor_pneus",
    sourceName: "valorPneus",
    nomeGerencial: "Valor do pneus do implemento",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pneus",
  },
  // --- TRECHO ---
  {
    entityType: "TRECHO",
    code: "trecho.vigencia",
    sourceName: "Vigencia",
    nomeGerencial: "Quinzena",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.unidade_cnpj",
    sourceName: "Unidade - CNPJ",
    nomeGerencial: "CNPJ da Unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.unidade_nome",
    sourceName: "Unidade - Nome",
    nomeGerencial: "Nome da Unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.unidade_sap",
    sourceName: "Unidade SAP",
    nomeGerencial: "Codigo da unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.unidade_tms",
    sourceName: "Unidade TMS",
    nomeGerencial: "Código TMS da Unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.unidade_promax_unb",
    sourceName: "Unidade - Promax UNB",
    nomeGerencial: "UNB Promax da Unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.unidade_regional",
    sourceName: "Unidade - Regional",
    nomeGerencial: "Regional da Unidade",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.operador_cnpj",
    sourceName: "Operador - CNPJ",
    nomeGerencial: "CNPJ do Transportador",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.operador_nome",
    sourceName: "Operador - Nome",
    nomeGerencial: "Nome do Transportador",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.operador_sap",
    sourceName: "Operador - SAP",
    nomeGerencial: "Codigo do Transportador",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.operador_tms",
    sourceName: "Operador - TMS",
    nomeGerencial: "Código TMS do Transportador",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.operador_promax",
    sourceName: "Operador - Promax",
    nomeGerencial: "Código Promax do Transportador",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.organizacao_de_compras",
    sourceName: "Organizacao de Compras",
    nomeGerencial: "Organização de Compras",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.prazo_pagamento",
    sourceName: "Prazo Pagamento",
    nomeGerencial: "Prazo de Pagamento",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.capacidade",
    sourceName: "Capacidade",
    nomeGerencial: "Capacidade de pallet",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.destino",
    sourceName: "Destino",
    nomeGerencial: "Nome unidade destino",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.destino_sap",
    sourceName: "destino SAP",
    nomeGerencial: "Codigo sap destino",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.destino_tms",
    sourceName: "destino TMS",
    nomeGerencial: "Codigo tms destino",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.f_mov",
    sourceName: "F-MOV",
    nomeGerencial: "Sinergia",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.origem",
    sourceName: "Origem",
    nomeGerencial: "Nome unidade origem",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.origem_sap",
    sourceName: "origem SAP",
    nomeGerencial: "Codigo sap origem",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.origem_tms",
    sourceName: "origem TMS",
    nomeGerencial: "Codigo tms origem",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.carga_horaria_motorista_puxada_mensal",
    sourceName: "cargaHorariaMotoristaPuxadaMensal",
    nomeGerencial: "Calculo de carga horaria do motorista mensal",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pessoal",
  },
  {
    entityType: "TRECHO",
    code: "trecho.carga_horaria_por_trajeto_minuto",
    sourceName: "cargaHorariaPorTrajetoMinuto",
    nomeGerencial: "Tempo total de ciclo",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.carga_horaria_por_trajeto_minuto_lucro",
    sourceName: "cargaHorariaPorTrajetoMinutoLucro",
    nomeGerencial: "Tempo total de ciclo - lucro",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.carga_horario_trajeto_dia",
    sourceName: "cargaHorarioTrajetoDia",
    nomeGerencial: "Tempo de deslocamento total do dia",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.carga_horario_trajeto_mes",
    sourceName: "cargaHorarioTrajetoMes",
    nomeGerencial: "Tempo de deslocamento total do mês",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.chave_trecho",
    sourceName: "chaveTrecho",
    nomeGerencial: "Chave do trecho - campo chave",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.cnpj_ida",
    sourceName: "cnpjIda",
    nomeGerencial: "CNPJ de faturamento da ida",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.cnpj_volta",
    sourceName: "cnpjVolta",
    nomeGerencial: "CNPJ de faturamento da volta",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.consumo_diesel_ajustado",
    sourceName: "consumoDieselAjustado",
    nomeGerencial: "Calculo de consumo de diesel ajustado de acordo com a carga",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Combustível",
  },
  {
    entityType: "TRECHO",
    code: "trecho.custo_da_diaria",
    sourceName: "custoDaDiaria",
    nomeGerencial: "Check de diaria ( valor)",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pessoal",
  },
  {
    entityType: "TRECHO",
    code: "trecho.custo_do_tr",
    sourceName: "custoDoTr",
    nomeGerencial: "Check de vale refeição (ticket refeição)",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pessoal",
  },
  {
    entityType: "TRECHO",
    code: "trecho.dias_mes",
    sourceName: "diasMes",
    nomeGerencial: "Calculo dias uteis",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.diesel_consumo_diesel_reais_km",
    sourceName: "dieselConsumoDieselReaisKM",
    nomeGerencial: "Calculo do diesel r$ km",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Combustível",
  },
  {
    entityType: "TRECHO",
    code: "trecho.diesel_consumo_km_l",
    sourceName: "dieselConsumoKmL",
    nomeGerencial: "Média de consumo trecho",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Combustível",
  },
  {
    entityType: "TRECHO",
    code: "trecho.fator_motorista_ajustado",
    sourceName: "fatorMotoristaAjustado",
    nomeGerencial: "Fator motorista ajustado",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pessoal",
  },
  {
    entityType: "TRECHO",
    code: "trecho.fator_motorista_indicado",
    sourceName: "fatorMotoristaIndicado",
    nomeGerencial: "Fator motorista benchmark",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pessoal",
  },
  {
    entityType: "TRECHO",
    code: "trecho.faturamento_destino_obrigatorio",
    sourceName: "faturamentoDestinoObrigatorio",
    nomeGerencial: "Faturamento obrigatório no destino",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_com_cprb",
    sourceName: "freteComCprb",
    nomeGerencial: "Calculo do frete para calculo do cprb",
    secaoDaDRE: "Receita bruta",
    categoriaDaDRE: "Frete do trecho — base de CPRB",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_ctrc",
    sourceName: "freteCtrc",
    nomeGerencial: "Calculo do valor do cte",
    secaoDaDRE: "Receita bruta",
    categoriaDaDRE: "Frete do trecho (CT-e)",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_liquido",
    sourceName: "freteLiquido",
    nomeGerencial: "Frete liquido sem imposto",
    secaoDaDRE: "Subtotal e margem",
    categoriaDaDRE: "Receita líquida",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_p_tms",
    sourceName: "fretePTms",
    nomeGerencial: "Frete com incidencia de cprb",
    secaoDaDRE: "Receita bruta",
    categoriaDaDRE: "Frete do trecho — valor no TMS",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_pis_cofins",
    sourceName: "fretePisCofins",
    nomeGerencial: "Calculo de pis e confins",
    secaoDaDRE: "(−) Deduções",
    categoriaDaDRE: "PIS/COFINS sobre a prestação",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_km_diesel",
    sourceName: "freteReaisKMDiesel",
    nomeGerencial: "R$/ km diesel",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Combustível",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_km_lavagem",
    sourceName: "freteReaisKMLavagem",
    nomeGerencial: "R$/ km lavagem",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Lavagem",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_km_lucro_variavel",
    sourceName: "freteReaisKMLucroVariavel",
    nomeGerencial: "R$/ km lucro variavel",
    secaoDaDRE: "Subtotal e margem",
    categoriaDaDRE: "Lucro variável do trecho",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_km_manutencao_carreta",
    sourceName: "freteReaisKMManutencaoCarreta",
    nomeGerencial: "R$/ km manutencao implemento",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_km_manutencao_cavalo",
    sourceName: "freteReaisKMManutencaoCavalo",
    nomeGerencial: "R$/ km manutencao",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_km_pedagio",
    sourceName: "freteReaisKMPedagio",
    nomeGerencial: "R$/ km pedagio",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pedágio",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_km_pneu",
    sourceName: "freteReaisKMPneu",
    nomeGerencial: "R$/ km pneu",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pneus",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_km_salario_variavel",
    sourceName: "freteReaisKMSalarioVariavel",
    nomeGerencial: "R$/ km premio produtividade",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pessoal",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_km_seguro",
    sourceName: "freteReaisKMSeguro",
    nomeGerencial: "R$/ km seguro",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Seguro de carga",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_viagem_diesel",
    sourceName: "freteReaisViagemDiesel",
    nomeGerencial: "Calculo de reais diesel",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Combustível",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_viagem_lavagem",
    sourceName: "freteReaisViagemLavagem",
    nomeGerencial: "Calculo de reais lavagem",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Lavagem",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_viagem_lucro_variavel",
    sourceName: "freteReaisViagemLucroVariavel",
    nomeGerencial: "Calculo de reais lucro variavel",
    secaoDaDRE: "Subtotal e margem",
    categoriaDaDRE: "Lucro variável do trecho",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_viagem_manutencao_carreta",
    sourceName: "freteReaisViagemManutencaoCarreta",
    nomeGerencial: "Calculo de reais manutenção carreta",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_viagem_manutencao_cavalo",
    sourceName: "freteReaisViagemManutencaoCavalo",
    nomeGerencial: "Calculo de reais manutenção cavalo",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_viagem_pedagio",
    sourceName: "freteReaisViagemPedagio",
    nomeGerencial: "Calculo de pedagio ou antecipação da tabela do frete minimo",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pedágio",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_viagem_pneus",
    sourceName: "freteReaisViagemPneus",
    nomeGerencial: "Calculo de reais pneus",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pneus",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_viagem_salario_variavel",
    sourceName: "freteReaisViagemSalarioVariavel",
    nomeGerencial: "Calculo de reais salario variavel",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pessoal",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frete_reais_viagem_seguro",
    sourceName: "freteReaisViagemSeguro",
    nomeGerencial: "Calculo de reais seguro",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Seguro de carga",
  },
  {
    entityType: "TRECHO",
    code: "trecho.frota_no_municipio",
    sourceName: "frotaNoMunicipio",
    nomeGerencial: "Frota no município",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.grade_carregamento",
    sourceName: "gradeCarregamento",
    nomeGerencial: "Calculo de turnos de fabricas",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.icms_iss",
    sourceName: "icmsIss",
    nomeGerencial: "Tributo aplicável (ICMS ou ISS)",
    secaoDaDRE: "(−) Deduções",
    categoriaDaDRE: "ICMS/ISS sobre a prestação",
  },
  {
    entityType: "TRECHO",
    code: "trecho.impostos_icms_iss",
    sourceName: "impostosIcmsIss",
    nomeGerencial: "Calculo de icms e confins",
    secaoDaDRE: "(−) Deduções",
    categoriaDaDRE: "ICMS/ISS sobre a prestação",
  },
  {
    entityType: "TRECHO",
    code: "trecho.km_ida",
    sourceName: "kmIda",
    nomeGerencial: "Km de ida",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.km_rodado",
    sourceName: "kmRodado",
    nomeGerencial: "Total de km ciclo",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.km_rodado_mes_por_equipe",
    sourceName: "kmRodadoMesPorEquipe",
    nomeGerencial: "Projeção de km rodado por mês",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.km_rodado_mes_por_equipe_lucro",
    sourceName: "kmRodadoMesPorEquipeLucro",
    nomeGerencial: "Projeção de km rodado por mês para lucro",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.km_volta",
    sourceName: "kmVolta",
    nomeGerencial: "Km de volta",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.lavagem_reais_km",
    sourceName: "lavagemReaisKm",
    nomeGerencial: "Calculo de reais lavagem",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Lavagem",
  },
  {
    entityType: "TRECHO",
    code: "trecho.lucro_variavel_reais_km",
    sourceName: "lucroVariavelReaisKm",
    nomeGerencial: "Calculo de reais lucro variavel",
    secaoDaDRE: "Subtotal e margem",
    categoriaDaDRE: "Lucro variável do trecho",
  },
  {
    entityType: "TRECHO",
    code: "trecho.manutencao_cavalo",
    sourceName: "manutencaoCavalo",
    nomeGerencial: "Parametro de manutenção cavalo r$",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "TRECHO",
    code: "trecho.manutencao_implemento_reaiskm",
    sourceName: "manutencaoImplementoReaiskm",
    nomeGerencial: "Parametro de manutenção implemento r$",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Manutenção",
  },
  {
    entityType: "TRECHO",
    code: "trecho.observacao",
    sourceName: "observacao",
    nomeGerencial: "Observação",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.pedagio",
    sourceName: "pedagio",
    nomeGerencial: "Calculo de pedagio caso o campo de reais km pedagio seja diferente de 0",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pedágio",
  },
  {
    entityType: "TRECHO",
    code: "trecho.pedagio_por_eixo_ida_volta",
    sourceName: "pedagioPorEixoIdaVolta",
    nomeGerencial: "Pedágio por eixo (ida e volta)",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pedágio",
  },
  {
    entityType: "TRECHO",
    code: "trecho.pedagio_reais_km",
    sourceName: "pedagioReaisKM",
    nomeGerencial: "R$ km pedagio",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pedágio",
  },
  {
    entityType: "TRECHO",
    code: "trecho.percentual_icms_iss",
    sourceName: "percentualIcmsIss",
    nomeGerencial: "Percentual de icms ou iss do trecho",
    secaoDaDRE: "(−) Deduções",
    categoriaDaDRE: "ICMS/ISS sobre a prestação",
  },
  {
    entityType: "TRECHO",
    code: "trecho.percentual_perda_descartavel",
    sourceName: "percentualPerdaDescartavel",
    nomeGerencial: "% De perda descartavel",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Combustível",
  },
  {
    entityType: "TRECHO",
    code: "trecho.percentual_perda_km",
    sourceName: "percentualPerdaKm",
    nomeGerencial: "% De perda km",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Combustível",
  },
  {
    entityType: "TRECHO",
    code: "trecho.percentual_perda_regiao",
    sourceName: "percentualPerdaRegiao",
    nomeGerencial: "% De perda regiao",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Combustível",
  },
  {
    entityType: "TRECHO",
    code: "trecho.pneu_custo_pneus_camaras_reais_km",
    sourceName: "pneuCustoPneusCamarasReaisKm",
    nomeGerencial: "R$ km custo de pneus camaras",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pneus",
  },
  {
    entityType: "TRECHO",
    code: "trecho.pneu_quantidade_de_pneus",
    sourceName: "pneuQuantidadeDePneus",
    nomeGerencial: "Calculo de quantidade de pneus",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pneus",
  },
  {
    entityType: "TRECHO",
    code: "trecho.pneu_valor_de_venda_da_carcaca",
    sourceName: "pneuValorDeVendaDaCarcaca",
    nomeGerencial: "Calculo do valor de venda da carcaça",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pneus",
  },
  {
    entityType: "TRECHO",
    code: "trecho.pneu_valor_medio_da_recapagem",
    sourceName: "pneuValorMedioDaRecapagem",
    nomeGerencial: "Valor médio da recapagem",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pneus",
  },
  {
    entityType: "TRECHO",
    code: "trecho.pneu_valor_medio_pneus",
    sourceName: "pneuValorMedioPneus",
    nomeGerencial: "Valor médio dos pneus nnovos",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pneus",
  },
  {
    entityType: "TRECHO",
    code: "trecho.pneu_vidautil_pneu",
    sourceName: "pneuVidautilPneu",
    nomeGerencial: "Vida util do pneu",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pneus",
  },
  {
    entityType: "TRECHO",
    code: "trecho.premio_produtividade_fator_motorista",
    sourceName: "premioProdutividadeFatorMotorista",
    nomeGerencial: "Calculo de produtividade fator motorista",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pessoal",
  },
  {
    entityType: "TRECHO",
    code: "trecho.premio_produtividade_km_rodado",
    sourceName: "premioProdutividadeKmRodado",
    nomeGerencial: "Calculo de produtividade km rodado",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pessoal",
  },
  {
    entityType: "TRECHO",
    code: "trecho.premio_produtividade_salario_variavel",
    sourceName: "premioProdutividadeSalarioVariavel",
    nomeGerencial: "Calculo de produtividade salario variavel",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pessoal",
  },
  {
    entityType: "TRECHO",
    code: "trecho.premio_produtividade_salario_variavel_reais_km",
    sourceName: "premioProdutividadeSalarioVariavelReaisKm",
    nomeGerencial: "Calculo de produtividade salario variavel r$ km",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pessoal",
  },
  {
    entityType: "TRECHO",
    code: "trecho.previsao_viagens",
    sourceName: "previsaoViagens",
    nomeGerencial: "Calculo de previsao de viagens",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.regiao_empurrada",
    sourceName: "regiaoEmpurrada",
    nomeGerencial: "Região da operação",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
  {
    entityType: "TRECHO",
    code: "trecho.seguro",
    sourceName: "seguro",
    nomeGerencial: "Seguro de carga",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Seguro de carga",
  },
  {
    entityType: "TRECHO",
    code: "trecho.seguro_reaiskm",
    sourceName: "seguroReaiskm",
    nomeGerencial: "R$ km seguro",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Seguro de carga",
  },
  {
    entityType: "TRECHO",
    code: "trecho.tempo_interno_destino",
    sourceName: "tempoInternoDestino",
    nomeGerencial: "Tma destino",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.tempo_interno_destino_lucro",
    sourceName: "tempoInternoDestinoLucro",
    nomeGerencial: "Tma destino lucro",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.tempo_interno_origem",
    sourceName: "tempoInternoOrigem",
    nomeGerencial: "Tma origem",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.tempo_interno_origem_lucro",
    sourceName: "tempoInternoOrigemLucro",
    nomeGerencial: "Tma origem lucro",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.tempo_refeicao_minuto",
    sourceName: "tempoRefeicaoMinuto",
    nomeGerencial: "Tempo de refeição",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.tempo_trajeto_fabrica_cd_minuto",
    sourceName: "tempoTrajetoFabricaCDMinuto",
    nomeGerencial: "Tempo de deslocamento fabrica x cdd",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.trecho_com_diaria",
    sourceName: "trechoComDiaria",
    nomeGerencial: "Check de trecho com ou sem diaria",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pessoal",
  },
  {
    entityType: "TRECHO",
    code: "trecho.trecho_com_vr",
    sourceName: "trechoComVr",
    nomeGerencial: "Check de trecho com ou sem vale refeição ( ticket refeição)",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pessoal",
  },
  {
    entityType: "TRECHO",
    code: "trecho.turno_empurrada",
    sourceName: "turnoEmpurrada",
    nomeGerencial: "Modelo de remuneração de equipe",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pessoal",
  },
  {
    entityType: "TRECHO",
    code: "trecho.turnos_fabrica",
    sourceName: "turnosFabrica",
    nomeGerencial: "Turnos de fabrica",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.velocidade_media_km_h",
    sourceName: "velocidadeMediaKmH",
    nomeGerencial: "Velocidade média do trecho",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Direcionador operacional",
  },
  {
    entityType: "TRECHO",
    code: "trecho.vidautil_ajustada_pneu",
    sourceName: "vidautilAjustadaPneu",
    nomeGerencial: "Vida util em km do pneu",
    secaoDaDRE: "(−) Custo variável",
    categoriaDaDRE: "Pneus",
  },
  {
    entityType: "TRECHO",
    code: "trecho.id",
    sourceName: "_id",
    nomeGerencial: "Identificador do registro",
    secaoDaDRE: "Não entra na DRE",
    categoriaDaDRE: "Cadastral",
  },
];

/**
 * O atributo declarado com este código, se houver.
 *
 * Existe para quem precisa de rótulo antes de existir dado: a tela de uma
 * lacuna de trecho não tem linha em `attribute` de onde tirar o nome, e
 * escrever `trecho.pedagio_cheio` na cara de quem opera é entregar o slug em
 * vez da resposta. O índice é montado uma vez, na carga do módulo — a lista é
 * fixa e cabe inteira em memória.
 */
const POR_CODIGO = new Map(CATALOGO_DECLARADO.map((a) => [a.code, a]));

export function atributoDeclarado(code: string): AtributoDeclarado | null {
  return POR_CODIGO.get(code) ?? null;
}
