export * from "./agregacao";
export * from "./significado";
export * from "./catalogo";
export * from "./semantics";
export * from "./taxonomy";
export * from "./engine";
export * from "./meaning";
export * from "./confirmations";
export * from "./versioning";
